version: '3'

services:
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: "12345"
    ports:
      - "5432:5432"
    volumes:
      - /Users/rveiga/projectsLearn/docker/Postgres:/var/lib/postgresql/data